# Generated by Django 4.0.6 on 2022-10-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('sex', models.IntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Yuuzu_Test',
            },
        ),
    ]
